// GENERATED by scripts/gen-tokens.py from the server repo's
// design/tokens.resolved.json. Do not edit: change design/tokens.json there,
// run `make tokens` there, then `make tokens` here.
import SwiftUI

enum Tokens {
    // Colors, each with its light and dark value.
    static let paper = Color(light: 0xF3F3F7, dark: 0x1B1713)
    static let surface = Color(light: 0xFFFFFF, dark: 0x28221D)
    static let sunken = Color(light: 0xE6E7EF, dark: 0x13100E)
    static let line = Color(light: 0xD3D6E3, dark: 0x473D33)
    static let muted = Color(light: 0x5A5D72, dark: 0xB9ADA2)
    static let ink = Color(light: 0x151728, dark: 0xF4EDE6)
    static let accent = Color(light: 0xF0567E, dark: 0xF0567E)
    static let onAccent = Color(light: 0x15182B, dark: 0x15182B)
    static let accentInk = Color(light: 0x8E405E, dark: 0xF77994)
    static let accentWash = Color(light: 0xFFE6E9, dark: 0x4C2E2E)
    static let ribbon1 = Color(light: 0x2B5CE6, dark: 0x6C8DFF)
    static let ribbon2 = Color(light: 0xD93F3A, dark: 0xF0716B)
    static let ribbon3 = Color(light: 0xE9B520, dark: 0xF2C94C)
    static let nose = Color(light: 0xE85F82, dark: 0xF58DA8)
    static let good = Color(light: 0x1B8F58, dark: 0x4CC38A)
    static let danger = Color(light: 0xC9352E, dark: 0xF0716B)

    /// Dark mode's lamp: the accent at this opacity, glowing from above the page.
    static let glowOpacity = (light: 0.00, dark: 0.10)

    enum Radius {
        static let field: CGFloat = 8
        static let card: CGFloat = 16
        static let sheet: CGFloat = 24
    }

    /// Width over height for every photo tile.
    static let photoRatio: CGFloat = 1 / 1

    enum FontFamily {
        static let display = "Bricolage Grotesque"
        static let body = "Instrument Sans"
        static let score = "Barlow Condensed"
    }

    /// What a vote is called: "treat" / "treats".
    static let voteWord = "treat"
    static func votes(_ n: Int) -> String { n == 1 ? voteWord : voteWord + "s" }
}
