#!/usr/bin/env python3
"""Generate FantasyCat/Design/Tokens.swift from the server repo's resolved design tokens.

The source of truth is ~/projects/fantasy-cat/design/tokens.json, compiled by
that repo's `make tokens` into design/tokens.resolved.json (and checked against
what Chrome renders). This script only transcribes. Run: make tokens
"""
import json, os, pathlib, sys

here = pathlib.Path(__file__).resolve().parent.parent
src = pathlib.Path(os.environ.get("FC_TOKENS", here.parent / "fantasy-cat" / "design" / "tokens.resolved.json"))
if not src.exists():
    sys.exit(f"gen-tokens: {src} not found. Clone the server repo next to this one, or set FC_TOKENS.")
t = json.loads(src.read_text())

def rgb(h):
    n = int(h[1:], 16)
    return f"0x{n:06X}"

names = list(t["color"]["light"].keys())
assert names == list(t["color"]["dark"].keys()), "light and dark must define the same colors"
colors = "\n".join(f'    static let {k} = Color(light: {rgb(t["color"]["light"][k])}, dark: {rgb(t["color"]["dark"][k])})' for k in names)
w, h = t["photoRatio"]
out = f'''// GENERATED by scripts/gen-tokens.py from the server repo's
// design/tokens.resolved.json. Do not edit: change design/tokens.json there,
// run `make tokens` there, then `make tokens` here.
import SwiftUI

enum Tokens {{
    // Colors, each with its light and dark value.
{colors}

    /// Dark mode's lamp: the accent at this opacity, glowing from above the page.
    static let glowOpacity = (light: {t["glow"]["light"]:.2f}, dark: {t["glow"]["dark"]:.2f})

    enum Radius {{
        static let field: CGFloat = {t["radius"]["field"]:g}
        static let card: CGFloat = {t["radius"]["card"]:g}
        static let sheet: CGFloat = {t["radius"]["sheet"]:g}
    }}

    /// Width over height for every photo tile.
    static let photoRatio: CGFloat = {w:g} / {h:g}

    enum FontFamily {{
        static let display = "{t["font"]["display"]}"
        static let body = "{t["font"]["body"]}"
        static let score = "{t["font"]["score"]}"
    }}

    /// What a vote is called: "{t["voteWord"]}" / "{t["voteWord"]}s".
    static let voteWord = "{t["voteWord"]}"
    static func votes(_ n: Int) -> String {{ n == 1 ? voteWord : voteWord + "s" }}
}}
'''
dest = here / "FantasyCat" / "Design" / "Tokens.swift"
dest.write_text(out)
print(f"gen-tokens: wrote {dest.relative_to(here)} ({len(names)} colors) from {src}")
